"""empty message

Revision ID: 5d0692c3b831
Revises: 
Create Date: 2023-04-11 16:03:42.160362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d0692c3b831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('admin_mail', schema=None) as batch_op:
        batch_op.alter_column('receiver',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=1024),
               nullable=True,
               existing_comment='收件人邮箱')

    with op.batch_alter_table('admin_power', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=19),
               type_=sa.Integer(),
               existing_comment='父类编号',
               existing_nullable=True)

    with op.batch_alter_table('admin_role_power', schema=None) as batch_op:
        batch_op.drop_constraint('admin_role_power_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('admin_role_power_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'admin_power', ['power_id'], ['id'])

    with op.batch_alter_table('admin_user_role', schema=None) as batch_op:
        batch_op.drop_constraint('admin_user_role_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('admin_user_role_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'admin_role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_user_role_ibfk_1', 'admin_role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('admin_user_role_ibfk_2', 'admin_user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('admin_role_power', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_role_power_ibfk_2', 'admin_role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('admin_role_power_ibfk_1', 'admin_power', ['power_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('admin_power', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_unicode_ci', length=19),
               existing_comment='父类编号',
               existing_nullable=True)

    with op.batch_alter_table('admin_mail', schema=None) as batch_op:
        batch_op.alter_column('receiver',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=1024),
               nullable=False,
               existing_comment='收件人邮箱')

    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
